### ISSUE TITLE
Deception IV: Blood Ties [PCSB00499]

### ISSUE THREAD

**Issue by Zangetsu38** [Vita3K/compatibility#1249]
# App summary
- App name: Deception IV: Blood Ties
- App serial: PCSB00499
- App version: 1.00

# Vita3K summary
- Version: v0.1.6
- Build number: 3023
- Commit hash: https://github.com/vita3k/vita3k/commit/cd96effc
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: Zangetsu 
- OS: Windows 10/macOS/Linux Distro, Kernel Version?
- CPU: AMD/Intel?
- GPU: AMD/NVIDIA/Intel?
- RAM: 16 GB

# Issues
- crash instant with lot dynarmic error

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/10777194/vita3k.log)

**Comment by othmanead** [comment]
# Vita3K summary
- Version: v0.1.8
- Build number: 3150
- Commit hash: https://github.com/vita3k/vita3k/commit/1b7e038d
- CPU backend: Dynarmic  

# Test environment summary
- Tested by: othmanead
- OS: Windows 11
- CPU: Intel i5-10300H
- GPU: RTX 3060 mobile
- RAM: 16 GB


# Issue: 
Game plays with audio bugs and minor graphical bugs
# Screenshots:
![image](https://github.com/Vita3K/compatibility/assets/106798110/9795f26a-f4c9-4a0e-8897-9eb4d6376f42)
![image](https://github.com/Vita3K/compatibility/assets/106798110/a58fc92c-a844-4871-b37c-60128b2970c1)



# Log


[vita3k.log](https://github.com/Vita3K/compatibility/files/11437017/vita3k.log)





# Recommended labels
- Ingame +
- Audio Bug
- Graphics Bug

**Comment by Slade1972** [comment]
# Vita3K summary
- Version: v0.2.0
- Build number: 3691
- Commit hash: https://github.com/vita3k/vita3k/commit/31826697
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: Slade 
- OS: Microsoft Windows 10 Professional (build 19045)
- CPU: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
- GPU: NVIDIA GeForce GTX 1060 6GB
- RAM: 16 GB

# Issues
- Graphics issues previously reported have been fixed.
- The spoken dialog is often played slowly with significant stutters, whilst other times it works fine.
- Due to the audio problems, the game is still considered Ingame +

# Screenshots
![dec1](https://github.com/user-attachments/assets/d455e7cb-b0ff-4a67-869f-e228725dad9f)
![dec2](https://github.com/user-attachments/assets/bacafba5-289f-4c85-96ef-43c9c60f4105)
![dec3](https://github.com/user-attachments/assets/931950ed-bff6-49a2-aa9f-a325528c65f1)
![dec4](https://github.com/user-attachments/assets/7023fb28-90b9-440f-af69-15ec939b56d5)


# Log
[vita3k.log](https://github.com/user-attachments/files/17946951/vita3k.log)


# Recommended labels

- Ingame +
- audio quality
- audio speed

**Comment by github-user1112** [comment]
Audio issues still exist

# Vita3K summary
Version: v0.2.1
Build number: 3965
Commit hash: https://github.com/Vita3K/commit/9916d86
GPU backend: Vulkan

# Test environment summary
Tested by: gtihub-user
OS: Linux Mint 22.3
CPU: AMD Ryzen 5 5600
GPU: Radeon Rx 6600
RAM: 16 GB
