### ISSUE TITLE
Uncharted: Golden Abyss™ [PCSF00012]

### ISSUE THREAD

**Issue by RoueSoify** [Vita3K/compatibility#1464]
# App summary
- App name: Uncharted: Golden Abyss™
- App serial: PCSF00012
- App version: 1.00

# Vita3K summary
- Version: v0.1.8
- Build number: 3149
- Commit hash: https://github.com/vita3k/vita3k/commit/4af2b07b
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: RoueSoify
- OS: Windows 11
- CPU: Intel Core i5-11400H @2.70GHz
- GPU: NVIDIA RTX 3060 Laptop
- RAM: 16 GB

# Issues
As far as I know this game seems to run the same as other versions of Uncharted GA :
Needs Vita3K to run as administrator.
No graphical glitches from 5x Internal Resolution and above.
The game seems to run at under 30fps, with sometimes 23fps and 15fps gameplay. (But this might be a weak GPU issue, idk)
There seems to be remnant of water effects on the screen (screenshot 4).

# Screenshots
![Capture d’écran (939)](https://github.com/Vita3K/compatibility/assets/52323610/13abac74-ab55-404c-b4c0-12c76ab26079)
![Capture d’écran (940)](https://github.com/Vita3K/compatibility/assets/52323610/9783edac-5064-4690-aabc-ef12d4e58ae3)
![Capture d’écran (941)](https://github.com/Vita3K/compatibility/assets/52323610/c03b4ef6-0db8-4c76-83cd-36be528dd97d)
![Capture d’écran (942)](https://github.com/Vita3K/compatibility/assets/52323610/2510d31c-6bbb-48f6-aa01-df9e80007480)

# Log

# Recommended labels
- Graphics Bug
- Audio Quality
- Ingame +

**Comment by Tha14** [comment]
https://github.com/Vita3K/compatibility/assets/5931740/3107240c-cb5d-4e1a-8696-cb7fc7b5ce04

Repeatable.

**Comment by RoueSoify** [comment]
Yes, juste tried it and had the same.
I am gonna try it on another version of the game (so not PCSF00012) and see if the problem is the same.
If so then just don't jump into the void, if not I would advise changing versions

**Comment by Tha14** [comment]
> 

I was using PCSA00029 so it's not version specific.

**Comment by RoueSoify** [comment]
Then I guess it's compatibility issue. It'll get fixed with time

**Comment by legolas119** [comment]
I'm running that game with latest Vita3k version but it has a lot of graphical glitches, the game is almost completely dark and really slow. I'm running it as administrator and i put Resolution = 5X as suggested, but i still have all those issues...is it normal? I have PCSF00012 version. Thanks

**Comment by Tha14** [comment]
> I'm running that game with latest Vita3k version but it has a lot of graphical glitches, the game is almost completely dark and really slow. I'm running it as administrator and i put Resolution = 5X as suggested, but i still have all those issues...is it normal? I have PCSF00012 version. Thanks

I haven't tried it in a long time so it's likely that there was some regression. Are you using vulkan or opengl as the renderer?

**Comment by Tha14** [comment]
Ok, looks like a regression when using the opengl renderer. It was working properly before when I last tried it. I'm attaching screenshots and the logs that get spammed constantly below.

OpenGL:
![image](https://github.com/Vita3K/compatibility/assets/5931740/48df2aa4-eb82-48f0-8694-3782933b4fb6)

```
[19:12:54.846] |E| [renderer::gl::color::translate_internal_format]: Unknown base format 0x41000000
[19:12:54.846] |E| [renderer::gl::color::translate_internal_format]: Unknown base format 0x41000000
[19:12:54.847] |E| [renderer::gl::color::translate_internal_format]: Unknown base format 0x41000000
[19:12:54.847] |E| [renderer::gl::color::translate_internal_format]: Unknown base format 0x41000000
[19:12:54.847] |E| [renderer::gl::color::translate_internal_format]: Unknown base format 0x41000000
[19:12:54.847] |E| [renderer::gl::color::translate_internal_format]: Unknown base format 0x10800000
[19:12:54.847] |E| [renderer::gl::color::translate_internal_format]: Unknown base format 0x41000000
[19:12:54.847] |E| [renderer::gl::color::translate_internal_format]: Unknown base format 0x10800000
[19:12:54.848] |E| [renderer::gl::color::translate_internal_format]: Unknown base format 0x41000000
[19:12:54.848] |E| [renderer::gl::color::translate_internal_format]: Unknown base format 0x41000000
[19:12:54.854] |E| [renderer::gl::color::translate_internal_format]: Unknown base format 0x41000000
[19:12:54.858] |E| [renderer::gl::color::translate_internal_format]: Unknown base format 0x41000000
[19:12:54.858] |E| [renderer::gl::color::translate_internal_format]: Unknown base format 0x41000000
[19:12:54.859] |E| [renderer::gl::color::translate_internal_format]: Unknown base format 0x41000000
[19:12:54.860] |E| [renderer::gl::color::translate_internal_format]: Unknown base format 0x41000000
[19:12:54.861] |E| [renderer::gl::color::translate_internal_format]: Unknown base format 0x41000000
[19:12:54.862] |E| [renderer::gl::color::translate_internal_format]: Unknown base format 0x41000000
[19:12:54.863] |E| [renderer::gl::color::translate_internal_format]: Unknown base format 0x41000000
```

Vulkan:
![image](https://github.com/Vita3K/compatibility/assets/5931740/7ef4e528-bf72-4fb6-971d-1a4d940a67b3)

**Comment by legolas119** [comment]
yeah you are right! with Vulkan and Resolution =5X the game works. Do you know if it is playable or does it crashes and it is not possible to finish it yet?
thanks!

**Comment by Mored4u** [comment]
Vita3k v0.2.0.3596-418f2343
GPU: Vulkan

![image](https://github.com/Vita3K/compatibility/assets/5413459/7ad96574-a34b-48d0-a312-0342df3838ba)

**Comment by jaloji** [comment]
With Vita3K v0.2.0 3654-10b8bf32, Audio glitch when loading screen but playable on v1.00 with Vulkan.
![Capture d’écran 2024-10-01 204243](https://github.com/user-attachments/assets/5035f40e-39b1-42e8-a246-eade800890f5)

But crashes on this frame with the v1.03
![Capture d’écran 2024-10-01 204501](https://github.com/user-attachments/assets/b2ac7c6c-fec4-4249-b51b-e3d879cdbae6)

**Comment by Arsconyl** [comment]
# Vita3K summary

Version: v0.2.1
Build number: 4066
Commit hash: https://github.com/Vita3K/Vita3K/commit/5ded8c78
CPU backend: Dynarmic
GPU backend: Vulkan

# Test environment summary

Tested by: Arsconyl
OS: Arch Linux
CPU: AMD Ryzen 7 5800X
GPU: AMD Radeon RX 9070 XT
RAM: 32 GB

Game version: 1.03

# Issues

Glitches at top and bottom of screen
Issue happens with resolution x1 (native), x1.75 and x5
Toggling CPU Optimizations on or off doesn't change anything
Toggling Renderer Accuracy Standard or High doesn't change anything
Setting Anisotropic Filtering to x1 or 16x doesn't change anything
Changing Screen filter doesn't change anything
Cleaning cache doesn't change anything

Sometimes, with native resolution, CPU Optimizations disabled, Renderer Accuracy Standard, Surface Sync disabled, Nearest Screen filter, Memory mapping disabled and clean cache, the glitches disappear after a moment.

Real shame because the game is stunning at high res.

# Logs

[vita3k.log](https://github.com/user-attachments/files/30558662/vita3k.log)

# Screenshots

<img width="4800" height="2720" alt="Image" src="https://github.com/user-attachments/assets/0e82614f-f209-4430-83ae-cc03a0a796e4" />
