### ISSUE TITLE
Hyperdevotion Noire: Goddess Black Heart [PCSB00701]

### ISSUE THREAD

**Issue by Slade1972** [Vita3K/compatibility#3049]
# App summary
- App name: Hyperdevotion Noire: Goddess Black Heart
- App serial: PCSB00701
- App version: 1.00

# Vita3K summary
- Version: v0.2.0
- Build number: 3703
- Commit hash: https://github.com/vita3k/vita3k/commit/0a3ba020
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: Slade 
- OS: Microsoft Windows 10 Professional (build 19045)
- CPU: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
- GPU: NVIDIA GeForce GTX 1060 6GB
- RAM: 16 GB

# Issues
- The audio stutters throughout the game. This includes music and spoken audio.
- The game crashes when attempting to save.
- The game itself seems to play well.

# Screenshots
![hdn1](https://github.com/user-attachments/assets/65764b89-97b3-4615-af92-5c2f425f8bf5)
![hdn3](https://github.com/user-attachments/assets/fd8e7488-19d6-4805-abe9-52fd69cb932a)
![hdn4](https://github.com/user-attachments/assets/45913007-7730-4296-963e-daa9ee900978)
![hdn5](https://github.com/user-attachments/assets/fd8faa52-677b-4c9e-92ac-743e57341327)

# Log
[PCSB00701 - [Hyperdevotion Noire_ Goddess Black Heart].log](https://github.com/user-attachments/files/18265303/PCSB00701.-.Hyperdevotion.Noire_.Goddess.Black.Heart.log)

# Recommended labels
- Ingame +
- Savedata bug
- crash
- audio quality

**Comment by Zangetsu38** [comment]
save works fine in my side 
![image](https://github.com/user-attachments/assets/ef99b0d3-44c6-43d8-85e2-6eeab76e0c6b)

**Comment by Slade1972** [comment]
> save works fine in my side 
> ok i have get crash in normal save after finish turorial

I can see you're also using a custom build that is newer than the one I was using...
If I get a crash like this, I always test more than once. I know I tested this at least twice, possibly a third time, just to confirm it wasn't some random issue.

**Comment by Zangetsu38** [comment]
i currently look for try fixing it, caused by empty param in moment create save

**Comment by Slade1972** [comment]
Very cool. It's nice to know that people do look at these test reports and they can help get things fixed.  Thanks!

Could the fix for this game help other games with a similar issue?

**Comment by Zangetsu38** [comment]
I don't know if other games have this problem, but there was a huge logic problem there

**Comment by Zangetsu38** [comment]
i have pushed fix here
https://github.com/Vita3K/Vita3K/pull/3483
you can see and try build when finished

**Comment by Slade1972** [comment]
I managed to get a build from that link (via Github build option). Thanks. I haven't tested in on this game yet, but I tested it on [another](https://github.com/Vita3K/compatibility/issues/3034), and the game went from 60fps down to 4-15 fps. It took me 20 minutes to get past the first level. That one still doesn't save with this error:

> |E| [export_sceSaveDataDialogGetResult::<lambda_1>::operator ()]: sceSaveDataDialogGetResult returned SCE_COMMON_DIALOG_ERROR_NOT_FINISHED (0x80020410)

The frame rate on this game is inconsistent with the build I made from your amended source (I don't get a good 30fps, it drops a lot down to 18-20fps). However, saving and loading does work.  Hopefully I'll remember to update this game in a a few days when an official build comes out.

**Comment by Zangetsu38** [comment]
This Build not affect performance 🤔

**Comment by Slade1972** [comment]
> This Build not affect performance 🤔

Yeah... It doesn't. Now.  No idea what changed, but I've just tried it again, and Habroxia 2 works fine now. It's running at the same frame rate as the other version.

I tested it against this game, and the frame rate is consistent here too. I need to update the report, as I'm getting low frame rates in some sections.

**Comment by Slade1972** [comment]
# Vita3K summary
- Version: v0.2.0
- Build number: 3706
- Commit hash: https://github.com/vita3k/vita3k/commit/baecccb0
- CPU backend: Dynarmic
- GPU backend: Vulkan


# Test environment summary
- Tested by: Slade 
- OS: Microsoft Windows 10 Professional (build 19045)
- CPU: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
- GPU: NVIDIA GeForce GTX 1060 6GB
- RAM: 16 GB

# Issues
- Slowdowns are evident as you progress in the game.
- The audio still stutters throughout.
- The fight sections work well enough.
- The save data bug has been fixed.


# Screenshots

![hydGB1](https://github.com/user-attachments/assets/d6a4145a-4974-4344-9f25-926d6e1101f7)
![hydGB2](https://github.com/user-attachments/assets/235c1b23-5569-4c06-a84e-dc88f24ceb33)
![hydGB3](https://github.com/user-attachments/assets/31bd4039-5870-4d07-9501-cd0383584d7c)
![hydGB4](https://github.com/user-attachments/assets/15b22570-76d0-49c6-a191-ce93fcf780ce)


# Log
[PCSB00701 - [Hyperdevotion Noire_ Goddess Black Heart].log](https://github.com/user-attachments/files/18279321/PCSB00701.-.Hyperdevotion.Noire_.Goddess.Black.Heart.log)


# Recommended labels
- Ingame +

**Comment by Slade1972** [comment]
Here's a saved game with $7,5,00,000 Credits.
It's early on in the game, it might make things easier to play.
 
[PCSB00701.zip](https://github.com/user-attachments/files/18279329/PCSB00701.zip)
