### ISSUE TITLE
Miracle Girls Festival [PCSG00610]

### ISSUE THREAD

**Issue by wangyw15** [Vita3K/compatibility#600]
# App summary
- App name: Miracle Girls Festival
- App serial: PCSG00610
- App version: 1.00

# Vita3K summary
- Version: v0.1.4
- Build number: 2465
- Commit hash: https://github.com/vita3k/vita3k/commit/15a37d5d 
- CPU backend: Dynarmic             

                          

# Test environment summary
- Tested by: wangyw15
- OS: Windows 11 22000.556
- CPU: 11th Gen Intel(R) Core(TM) i7-11800H
- GPU: NVIDIA GeForce RTX 3060 Laptop GPU
- RAM: 16 GB

# Issues
 - stuck at the splash screen

# Screenshots
![Vita3K_v0 1 4_2465-15a37d5d__MIRACLE_GIRLS_FESTIV_2022-03-24_12-30-23](https://user-images.githubusercontent.com/18070676/159842725-15b4a6e2-3ade-4f33-9d4b-001d47895593.png)
![Vita3K_v0 1 4_2465-15a37d5d__MIRACLE_GIRLS_FESTIV_2022-03-24_12-40-41](https://user-images.githubusercontent.com/18070676/159843629-fb16393e-7b36-4263-86f3-fe05b80dd2d6.png)

# Log

[console.log](https://github.com/Vita3K/compatibility/files/8338486/console.log)
[vita3k.log](https://github.com/Vita3K/compatibility/files/8338495/vita3k.log)

# Recommended labels

- crash

**Comment by wgc131419** [comment]
现在都2947版本了这个游戏还玩不了 @Macdu

**Comment by tetorapott** [comment]
can't proceed beyond this screen
![bandicam 2023-02-08 00-02-09-004](https://user-images.githubusercontent.com/124598498/217282795-87fe2c71-948a-49e6-a375-741cc05db406.jpg)


[vita3k.log](https://github.com/Vita3K/compatibility/files/10676473/vita3k.log)

**Comment by tetorapott** [comment]
**Vita3K summary**
・Version: v0.1.6
・Build number: 3019
・Commit hash: https://github.com/Vita3K/Vita3K/commit/15d57ac2
・CPU backend: Dynarmic


**Test environment summary**
・Tested by: tetorapott
・OS: Windows 11
・CPU:Intel Core i7 -12700K
・GPU: NVIDIA GeForce RTX 3070
・RAM: 32 GB

**Issues**
 playable
 but the back monitor doesn't display
![タイトルなし](https://user-images.githubusercontent.com/124598498/219520252-e3902aea-b94d-4d62-a117-14bd1d0dea9b.png)
![タイトルなし2](https://user-images.githubusercontent.com/124598498/219525262-5f1e4741-885d-4554-b5c1-2e1df3550396.png)
[vita3k.log](https://github.com/Vita3K/compatibility/files/10762337/vita3k.log)

**Comment by Zangetsu38** [comment]
# Vita3K summary
- Version: v0.1.6
- Build number: 3024
- Commit hash: https://github.com/Vita3K/Vita3K/commit/09dd3e81
- CPU backend: Dynarmic
- GPU backend: Vulkan
                          

# Test environment summary
- Tested by: tetorapott
- OS: Windows 11 Pro
- CPU: 12th Gen Intel(R) Core(TM) i7-12700K
- GPU: NVIDIA GeForce RTX 3070
- RAM: 32.0 GB

# Issues
playable
the back monitor doesn't display



# Screenshots
![タイトルなし](https://user-images.githubusercontent.com/124598498/220377892-733bdbcb-ba61-43fe-8b28-ceaf19452086.png)
![タイトルなし2](https://user-images.githubusercontent.com/124598498/220378189-433ce9a6-5853-4717-8adf-f6958ed12bb6.png)



OpenGL
- "Disable surface sync" OFF, the back monitor display
- slowly


![タイトルなし3](https://user-images.githubusercontent.com/124598498/220757967-27dc827d-bfd6-45b0-b96f-19a422368a37.png)

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/10794643/vita3k.log)

# Recommended labels

- Playable
- vulkan issue
- video player bug?

**Comment by XYYYLRRH** [comment]
# Vita3K summary
Version: v0.1.6
Build number: 3101
Commit hash: [Vita3K/Vita3K@8623b516](https://github.com/Vita3K/Vita3K/commit/8623b516)
CPU backend: Dynarmic
# Test environment summary
Tested by: XYYYLRRH
OS: Windows 11 22621.1555
CPU: AMD Ryzen 7 5800H
GPU: NVIDIA GeForce RTX 3060 Laptop GPU
RAM: 16 GB
# Issues
The back monitors display, but sometimes it runs slowly.
# Screenshots
The back monitors finally displays when using Vulkan (enable surface sync), and most of time it runs normally (30fps).
![miracle1](https://user-images.githubusercontent.com/25168873/232062743-bc087eb3-5252-47f5-a720-374d707e0731.jpg)
But at some time, the frame drops (even FXAA off, 1x resolution and 1x filtering).
![miracle2](https://user-images.githubusercontent.com/25168873/232066595-bb6f85ef-dcf8-4ecf-baa6-164523519350.jpg)
In Build 3091, the back monitor displays "RENDER" instead of "MOVIE", and it runs normally (30fps) at all time. Actually at this time, the back monitor is not displaying a video, instead it's displaying real-time performance.
![miracle3](https://user-images.githubusercontent.com/25168873/232066554-b0660197-ae11-4e5d-ae06-cc60572cb0a8.jpg)
# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/11233763/vita3k.log)

**Comment by XYYYLRRH** [comment]
In addition,
1. When the back monitor displays real-time performance (same scene),
- PSV(PS TV):
![1759960122](https://user-images.githubusercontent.com/25168873/232087703-7f3abc6b-4f3d-4fbb-b761-71ecec2dbc3b.jpg)
- Vita3k:
![miracle4](https://user-images.githubusercontent.com/25168873/232086816-20664017-d164-4464-8872-43ac17eb1679.jpg)
In PSV,  the back monitor focuses on the performers, so the back monitor is not fully displayed on the back monitor. However, in Vita3k, the back monitor displays all the stage, so the frame drops.
2. In Vita3k, after the back monitor displays the information of the song, it displays a green screen in a short time.
![miracle5](https://user-images.githubusercontent.com/25168873/232091853-10b6a740-9797-48d3-a468-62106c94d28c.jpg)
3. When "Disable surface sync" is OFF, no matter using Vulkan or OpenGL, Vita3k keeps running slowly after the back monitors displayed real-time performance. 
4. When "Disable surface sync" is ON, the back monitor doesn't display using Vulkan, and the whole game screen displays inaccurately when using OpenGL, like the following picture:
![miracle6](https://user-images.githubusercontent.com/25168873/232094698-c54f7696-4ad1-4421-979e-a83c6e598dde.jpg)

**Comment by Pikota3124** [comment]
# Vita3K summary

- Version: 0.1.8
- Build number: 3195
- CPU backend: Dynarmic.
- GPU backend: Either Vulkan or Opengl not working

# Test environment summary

- Tested by: Pikota
- OS: Windows 11
- CPU: AMD R7 5700X
- GPU: AMD RX 6700XT
- RAM: 32 GB

# Issues

Stuck at the splash screen, doesnt matter what config i use

# Screenshots

<img width="1920" alt="Screenshot_10" src="https://github.com/Vita3K/compatibility/assets/41958666/049d7113-752e-41bf-b950-4115943bf895">

# Log

[vita3k.log](https://github.com/Vita3K/compatibility/files/11642288/vita3k.log)

# Recommended labels

- Intro

**Comment by Pikota3124** [comment]
# Vita3K summary

Version: v0.1.8
Build number: 3195
CPU backend: Dynarmic

Tested by: Pikota
OS: Windows 11
CPU: AMD Ryzen 7 5700X
GPU: AMD RX 6700XT
RAM: 32GB

# Issues

That lightning stick are way too brighter or overexposed

Original game

![Screenshot_2](https://github.com/Vita3K/compatibility/assets/41958666/5b3c5a26-8691-4eea-b671-e90a287d796a)

Emulated game

![Screenshot_1](https://github.com/Vita3K/compatibility/assets/41958666/ddd91b60-6062-43d4-b0fb-75b75bac2b96)


# Log

[vita3k.log](https://github.com/Vita3K/compatibility/files/11643525/vita3k.log)

# Recommended labels

- Graphics Bug

**Comment by Pikota3124** [comment]
Back monitor is already fixed, no "render/movie" display and now fps are stable at 30fps. 

Still the audience lights are bugged.

**_Tested on build 3203_**

**Comment by Panderner** [comment]
The audience lights bug is most likely an upscaling issue.

**Comment by Pikota3124** [comment]
Its Vulkan issue(maybe because it has no Vsync?), because if its played on OpenGL there is no issue with lights.



Also on new versions of Vita3K game is crashing randomly, last stable build i use is 3209, log here.

[vita3k.log](https://github.com/Vita3K/compatibility/files/12061274/vita3k.log)

**Comment by nishinji** [comment]
vulkan bug already fixed recently (bug remain when upscaling)
![image](https://github.com/Vita3K/compatibility/assets/107111782/965d0cba-84d7-4b13-8249-59d621bbc194)

**Comment by HotoRas** [comment]
Unplayable on Android
